#!/bin/bash

# install node-exporter
if [[ ! -e /opt/node-exporter ]]; then
    cd /tmp/
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-amd64.tar.gz
    tar zxf node_exporter-1.0.0.linux-amd64.tar.gz
    mv node_exporter-1.0.0.linux-amd64/node_exporter /opt/
    cat <<"EOF"> //lib/systemd/system/node-exporter.service
[Unit]
Description=node_exporter
Documentation=https://prometheus.io/
After=network.target
[Service]
Type=simple
User=root
ExecStart=/opt/node_exporter
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl start node-exporter
    systemctl enable node-exporter
    ps aux | grep node-exporter
fi

