#!/bin/bash

round=$1

if [[ $2 == "pod" ]]; then
    ./2020-06-04-summary.sh | grep pod-svc | awk -F "." '{print $3,$4}' | grep "^${round}" | awk '{print $2,$3}' | sort -n
else
./2020-06-04-summary.sh | grep ingress | awk -F "." '{print $4,$5}' | grep "^${round}" | awk '{print $2,$3}' | sort -n
fi
