#!/usr/bin/expect

set host [lindex $argv 0]

eval spawn ssh -oStrictHostKeyChecking=no -oCheckHostIP=no azureuser@${host}

expect "\\$"
send "sudo apt-get install -y wrk \r"

expect "\\$"
send "exit\r"


expect eof
