# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  http2-max-header-size: 32k
  keep-alive: "600"
  keep-alive-requests: "1000000"
  limit-conn-status-code: "429"
  limit-req-status-code: "429"
  proxy-body-size: 16m
  proxy_buffer_size: 32k
  ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384
  ssl-prefer-server-ciphers: "True"
  ssl-protocols: TLSv1.2
  upstream-keepalive-connections: "1000"
  upstream-keepalive-requests: "1000000"
  upstream-keepalive-timeout: "600"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: nginx-configuration
  namespace: default
